version: "3.8"

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: controle-livros-frontend
    restart: always
    networks:
      - host
    environment:
      - NEXTAUTH_URL="https://api-controle-livros.anapolis.go.gov.br/"
      - NEXTAUTH_SECRET="cyytdoNtqxVc151S+vLNHSOZ6IgT3c2wp6HwLnVtHO0="

  nginx:
    build: ./nginx
    ports:
      - 3055:80
    restart: always
    depends_on:
      - frontend
    networks:
      - host

networks:
  host:
    driver: bridge
