version: "3.8"

services:
  frontend:
    build:
      dockerfile: Dockerfile
    networks:
      - host

  nginx:
    build: ./nginx
    ports:
      - 3030:80
    depends_on:
      - frontend
    networks:
      - host

networks:
  host:
    driver: bridge
